SUPABASE_URL = "https://ydybmnhpqpcvkhudxiol.supabase.co"
SUPABASE_ANON_KEY = "sb_publishable_CKsQPpL4rhGscprMc3KFfA_6NUEI-6c"

# 이메일 설정 (선택)
SMTP_SERVER = "smtp.gmail.com"
SMTP_PORT = 587
SENDER_EMAIL = "younjc7450@gmail.com"
SENDER_PASSWORD = "mxee bmbe mzch iuty"